server:
  port: 8085
spring:
  application:
    name: receipt-validator-service
  data:
    mongodb:
      uri: mongodb://${MONGO_DATABASE_USERNAME}:${MONGO_DATABASE_PASSWORD}@localhost:27017/${MONGO_DATABASE_NAME}?authSource=admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
      transaction-id-prefix: receipt-validator-service-${random.value}-
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      group-id: receipt-events
      isolation-level: read_committed
logging:
  level:
    root: info
    com.example.receiptvalidatorservice: DEBUG
    org.springframework.kafka.transaction: DEBUG
    org.apache.kafka.clients.producer.internals.TransactionManager: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
import:
  json-schema: classpath:schemas/schema.json
custom:
  kafka:
    error-handler:
      backoff-interval: 3000
      max-attempts: 5

    topics:
      receipt-validate-input-topic-events:
        partitions: 3
        replicas: 3
        min-insync-replicas: 2
      receipt-validate-output-topic-events:
        partitions: 3
        replicas: 3
        min-insync-replicas: 2
      receipt-validate-errors-records:
        partitions: 3
        replicas: 3
        min-insync-replicas: 2
outbox:
  batch-size: 100